package me.hapyl.spigotutils.module.entity.packet;

import me.hapyl.spigotutils.module.annotate.TestedOn;
import me.hapyl.spigotutils.module.annotate.Version;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ambient.EntityBat;
import net.minecraft.world.entity.animal.*;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.camel.Camel;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.horse.*;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.boss.enderdragon.EntityEnderCrystal;
import net.minecraft.world.entity.boss.enderdragon.EntityEnderDragon;
import net.minecraft.world.entity.boss.wither.EntityWither;
import net.minecraft.world.entity.decoration.*;
import net.minecraft.world.entity.item.EntityFallingBlock;
import net.minecraft.world.entity.item.EntityItem;
import net.minecraft.world.entity.item.EntityTNTPrimed;
import net.minecraft.world.entity.monster.*;
import net.minecraft.world.entity.monster.hoglin.EntityHoglin;
import net.minecraft.world.entity.monster.piglin.EntityPiglin;
import net.minecraft.world.entity.monster.piglin.EntityPiglinBrute;
import net.minecraft.world.entity.monster.warden.Warden;
import net.minecraft.world.entity.npc.EntityVillager;
import net.minecraft.world.entity.npc.EntityVillagerTrader;
import net.minecraft.world.entity.player.EntityHuman;
import net.minecraft.world.entity.projectile.*;
import net.minecraft.world.entity.vehicle.*;

import java.util.Map;

/**
 * Contains all NMS entity types, mapped with a readable name.
 */
@SuppressWarnings("unused")
@TestedOn(version = Version.V1_20_2)
public final class NMSEntityType {

    public static final EntityTypes<Allay> ALLAY = EntityTypes.b;
    public static final EntityTypes<EntityAreaEffectCloud> AREA_EFFECT_CLOUD = EntityTypes.c;
    public static final EntityTypes<EntityArmorStand> ARMOR_STAND = EntityTypes.d;
    public static final EntityTypes<EntityTippedArrow> TIPPED_ARROW = EntityTypes.e;
    public static final EntityTypes<Axolotl> AXOLOTL = EntityTypes.f;
    public static final EntityTypes<EntityBat> BAT = EntityTypes.g;
    public static final EntityTypes<EntityBee> BEE = EntityTypes.h;
    public static final EntityTypes<EntityBlaze> BLAZE = EntityTypes.i;
    public static final EntityTypes<Display.BlockDisplay> BLOCK_DISPLAY = EntityTypes.j;
    public static final EntityTypes<EntityBoat> BOAT = EntityTypes.k;
    public static final EntityTypes<Camel> CAMEL = EntityTypes.l;
    public static final EntityTypes<EntityCat> CAT = EntityTypes.m;
    public static final EntityTypes<EntityCaveSpider> CAVE_SPIDER = EntityTypes.n;
    public static final EntityTypes<ChestBoat> CHEST_BOAT = EntityTypes.o;
    public static final EntityTypes<EntityMinecartChest> MINECART_CHEST = EntityTypes.p;
    public static final EntityTypes<EntityChicken> CHICKEN = EntityTypes.q;
    public static final EntityTypes<EntityCod> COD = EntityTypes.r;
    public static final EntityTypes<EntityMinecartCommandBlock> MINECART_COMMAND_BLOCK = EntityTypes.s;
    public static final EntityTypes<EntityCow> COW = EntityTypes.t;
    public static final EntityTypes<EntityCreeper> CREEPER = EntityTypes.u;
    public static final EntityTypes<EntityDolphin> DOLPHIN = EntityTypes.v;
    public static final EntityTypes<EntityHorseDonkey> HORSE_DONKEY = EntityTypes.w;
    public static final EntityTypes<EntityDragonFireball> DRAGON_FIREBALL = EntityTypes.x;
    public static final EntityTypes<EntityDrowned> DROWNED = EntityTypes.y;
    public static final EntityTypes<EntityEgg> EGG = EntityTypes.z;
    public static final EntityTypes<EntityGuardianElder> GUARDIAN_ELDER = EntityTypes.A;
    public static final EntityTypes<EntityEnderCrystal> ENDER_CRYSTAL = EntityTypes.B;
    public static final EntityTypes<EntityEnderDragon> ENDER_DRAGON = EntityTypes.C;
    public static final EntityTypes<EntityEnderPearl> ENDER_PEARL = EntityTypes.D;
    public static final EntityTypes<EntityEnderman> ENDERMAN = EntityTypes.E;
    public static final EntityTypes<EntityEndermite> ENDERMITE = EntityTypes.F;
    public static final EntityTypes<EntityEvoker> EVOKER = EntityTypes.G;
    public static final EntityTypes<EntityEvokerFangs> EVOKER_FANGS = EntityTypes.H;
    public static final EntityTypes<EntityThrownExpBottle> THROWN_EXP_BOTTLE = EntityTypes.I;
    public static final EntityTypes<EntityExperienceOrb> EXPERIENCE_ORB = EntityTypes.J;
    public static final EntityTypes<EntityEnderSignal> ENDER_SIGNAL = EntityTypes.K;
    public static final EntityTypes<EntityFallingBlock> FALLING_BLOCK = EntityTypes.L;
    public static final EntityTypes<EntityFireworks> FIREWORKS = EntityTypes.M;
    public static final EntityTypes<EntityFox> FOX = EntityTypes.N;
    public static final EntityTypes<Frog> FROG = EntityTypes.O;
    public static final EntityTypes<EntityMinecartFurnace> MINECART_FURNACE = EntityTypes.P;
    public static final EntityTypes<EntityGhast> GHAST = EntityTypes.Q;
    public static final EntityTypes<EntityGiantZombie> GIANT_ZOMBIE = EntityTypes.R;
    public static final EntityTypes<GlowItemFrame> GLOW_ITEM_FRAME = EntityTypes.S;
    public static final EntityTypes<GlowSquid> GLOW_SQUID = EntityTypes.T;
    public static final EntityTypes<Goat> GOAT = EntityTypes.U;
    public static final EntityTypes<EntityGuardian> GUARDIAN = EntityTypes.V;
    public static final EntityTypes<EntityHoglin> HOGLIN = EntityTypes.W;
    public static final EntityTypes<EntityMinecartHopper> MINECART_HOPPER = EntityTypes.X;
    public static final EntityTypes<EntityHorse> HORSE = EntityTypes.Y;
    public static final EntityTypes<EntityZombieHusk> ZOMBIE_HUSK = EntityTypes.Z;
    public static final EntityTypes<EntityIllagerIllusioner> ILLUSIONER = EntityTypes.aa;
    public static final EntityTypes<Interaction> INTERACTION = EntityTypes.ab;
    public static final EntityTypes<EntityIronGolem> IRON_GOLEM = EntityTypes.ac;
    public static final EntityTypes<EntityItem> ITEM = EntityTypes.ad;
    public static final EntityTypes<Display.ItemDisplay> ITEM_DISPLAY = EntityTypes.ae;
    public static final EntityTypes<EntityItemFrame> ITEM_FRAME = EntityTypes.af;
    public static final EntityTypes<EntityLargeFireball> LARGE_FIREBALL = EntityTypes.ag;
    public static final EntityTypes<EntityLeash> LEASH = EntityTypes.ah;
    public static final EntityTypes<EntityLightning> LIGHTNING = EntityTypes.ai;
    public static final EntityTypes<EntityLlama> LLAMA = EntityTypes.aj;
    public static final EntityTypes<EntityLlamaSpit> LLAMA_SPIT = EntityTypes.ak;
    public static final EntityTypes<EntityMagmaCube> MAGMA_CUBE = EntityTypes.al;
    public static final EntityTypes<Marker> MARKER = EntityTypes.am;
    public static final EntityTypes<EntityMinecartRideable> MINECART_RIDEABLE = EntityTypes.an;
    public static final EntityTypes<EntityMushroomCow> MUSHROOM_COW = EntityTypes.ao;
    public static final EntityTypes<EntityHorseMule> HORSE_MULE = EntityTypes.ap;
    public static final EntityTypes<EntityOcelot> OCELOT = EntityTypes.aq;
    public static final EntityTypes<EntityPainting> PAINTING = EntityTypes.ar;
    public static final EntityTypes<EntityPanda> PANDA = EntityTypes.as;
    public static final EntityTypes<EntityParrot> PARROT = EntityTypes.at;
    public static final EntityTypes<EntityPhantom> PHANTOM = EntityTypes.au;
    public static final EntityTypes<EntityPig> PIG = EntityTypes.av;
    public static final EntityTypes<EntityPiglin> PIGLIN = EntityTypes.aw;
    public static final EntityTypes<EntityPiglinBrute> PIGLIN_BRUTE = EntityTypes.ax;
    public static final EntityTypes<EntityPillager> PILLAGER = EntityTypes.ay;
    public static final EntityTypes<EntityPolarBear> POLAR_BEAR = EntityTypes.az;
    public static final EntityTypes<EntityPotion> POTION = EntityTypes.aA;
    public static final EntityTypes<EntityPufferFish> PUFFER_FISH = EntityTypes.aB;
    public static final EntityTypes<EntityRabbit> RABBIT = EntityTypes.aC;
    public static final EntityTypes<EntityRavager> RAVAGER = EntityTypes.aD;
    public static final EntityTypes<EntitySalmon> SALMON = EntityTypes.aE;
    public static final EntityTypes<EntitySheep> SHEEP = EntityTypes.aF;
    public static final EntityTypes<EntityShulker> SHULKER = EntityTypes.aG;
    public static final EntityTypes<EntityShulkerBullet> SHULKER_BULLET = EntityTypes.aH;
    public static final EntityTypes<EntitySilverfish> SILVERFISH = EntityTypes.aI;
    public static final EntityTypes<EntitySkeleton> SKELETON = EntityTypes.aJ;
    public static final EntityTypes<EntityHorseSkeleton> HORSE_SKELETON = EntityTypes.aK;
    public static final EntityTypes<EntitySlime> SLIME = EntityTypes.aL;
    public static final EntityTypes<EntitySmallFireball> SMALL_FIREBALL = EntityTypes.aM;
    public static final EntityTypes<Sniffer> SNIFFER = EntityTypes.aN;
    public static final EntityTypes<EntitySnowman> SNOWMAN = EntityTypes.aO;
    public static final EntityTypes<EntitySnowball> SNOWBALL = EntityTypes.aP;
    public static final EntityTypes<EntityMinecartMobSpawner> MINECART_MOB_SPAWNER = EntityTypes.aQ;
    public static final EntityTypes<EntitySpectralArrow> SPECTRAL_ARROW = EntityTypes.aR;
    public static final EntityTypes<EntitySpider> SPIDER = EntityTypes.aS;
    public static final EntityTypes<EntitySquid> SQUID = EntityTypes.aT;
    public static final EntityTypes<EntitySkeletonStray> SKELETON_STRAY = EntityTypes.aU;
    public static final EntityTypes<EntityStrider> STRIDER = EntityTypes.aV;
    public static final EntityTypes<Tadpole> TADPOLE = EntityTypes.aW;
    public static final EntityTypes<Display.TextDisplay> TEXT_DISPLAY = EntityTypes.aX;
    public static final EntityTypes<EntityTNTPrimed> TNT_PRIMED = EntityTypes.aY;
    public static final EntityTypes<EntityMinecartTNT> MINECART_TNT = EntityTypes.aZ;
    public static final EntityTypes<EntityLlamaTrader> LLAMA_TRADER = EntityTypes.ba;
    public static final EntityTypes<EntityThrownTrident> THROWN_TRIDENT = EntityTypes.bb;
    public static final EntityTypes<EntityTropicalFish> TROPICAL_FISH = EntityTypes.bc;
    public static final EntityTypes<EntityTurtle> TURTLE = EntityTypes.bd;
    public static final EntityTypes<EntityVex> VEX = EntityTypes.be;
    public static final EntityTypes<EntityVillager> VILLAGER = EntityTypes.bf;
    public static final EntityTypes<EntityVindicator> VINDICATOR = EntityTypes.bg;
    public static final EntityTypes<EntityVillagerTrader> VILLAGER_TRADER = EntityTypes.bh;
    public static final EntityTypes<Warden> WARDEN = EntityTypes.bi;
    public static final EntityTypes<EntityWitch> WITCH = EntityTypes.bj;
    public static final EntityTypes<EntityWither> WITHER = EntityTypes.bk;
    public static final EntityTypes<EntitySkeletonWither> SKELETON_WITHER = EntityTypes.bl;
    public static final EntityTypes<EntityWitherSkull> WITHER_SKULL = EntityTypes.bm;
    public static final EntityTypes<EntityWolf> WOLF = EntityTypes.bn;
    public static final EntityTypes<EntityZoglin> ZOGLIN = EntityTypes.bo;
    public static final EntityTypes<EntityZombie> ZOMBIE = EntityTypes.bp;
    public static final EntityTypes<EntityHorseZombie> HORSE_ZOMBIE = EntityTypes.bq;
    public static final EntityTypes<EntityZombieVillager> ZOMBIE_VILLAGER = EntityTypes.br;
    public static final EntityTypes<EntityPigZombie> PIG_ZOMBIE = EntityTypes.bs;
    public static final EntityTypes<EntityHuman> HUMAN = EntityTypes.bt;
    public static final EntityTypes<EntityFishingHook> FISHING_HOOK = EntityTypes.bu;

}
